[package]
name = "p4inz"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
axum = "0.8.9"
p4inz-api = { version = "0.1.0", path = "../../crates/api" }
p4inz-config = { version = "0.1.0", path = "../../crates/config" }
p4inz-database = { version = "0.1.0", path = "../../crates/database" }
p4inz-infrastructure = { version = "0.1.0", path = "../../crates/infrastructure" }
p4inz-observability = { version = "0.1.0", path = "../../crates/observability" }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net", "signal"] }
tracing = { version = "0.1.44", default-features = false, features = ["std"] }
