[package]
name = "p4inz-ai"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
p4inz-common = { version = "0.1.0", path = "../common" }
p4inz-errors = { version = "0.1.0", path = "../errors" }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["macros", "rt", "net"] }
