[package]
name = "p4inz-audit"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
p4inz-errors = { version = "0.1.0", path = "../errors" }
thiserror = "2.0.20"
tracing = { version = "0.1.44", default-features = false, features = ["std"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }
