[package]
name = "p4inz-knowledge"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
p4inz-domain = { version = "0.1.0", path = "../domain" }
p4inz-errors = { version = "0.1.0", path = "../errors" }
thiserror = "2.0.20"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }
